import type { NextPage } from 'next'
import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { title } from 'process'
import HighlightsSection from '../Components/highlights-section'
import ProfileSection from '../Components/profile-section'
import ProjectSections from '../Components/project-sections'
import WelcomeSection from '../Components/welcome-section'

import styles from '../styles/Home.module.css'
import { format } from 'path'

const Home: NextPage = () => {

  useEffect(() => {
    window.onbeforeunload = function () {
      window.scrollTo(0, 0);
    }
  });

  const sampleData = {

    title: 'Sample',
    imgUrl: 'http://placehold.jp/878787/ffffff/200x200.png?text=Sample'

  };


  return (
    <div className={styles.container}>
      <Head>
        <title>App Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WelcomeSection/>
        <ProfileSection/>
        <HighlightsSection/>
        <ProjectSections title='Test' items={[sampleData, sampleData, sampleData, sampleData, sampleData]}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
